version: '3.8'

services:
  # FastAPI バックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bubble-backend
    ports:
      - "8000:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - bubble-network

  # Next.js Webアプリ
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: bubble-web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env.local
    volumes:
      - ./web:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - bubble-network
    depends_on:
      - backend

networks:
  bubble-network:
    driver: bridge
